### ISSUE TITLE
 Caught an exception while recovering queue : channel is already closed due to clean channel shutdown

### ISSUE THREAD

**Issue by pocman** [ScalaConsultants/reactive-rabbit#47]
To replicate, run:
`Source.fromPublisher(Connection().consume(queue = queue)).runWith(Sink.ignore)`
with application.conf : 
```
amqp {
  heartbeat = 2s
  automatic-recovery = true
  recovery-interval = 2s
}
```
Kill rabbitmq-server and restart.
I will raise :
```
Caught an exception when recovering topology Caught an exception while recovering queue admin.assignments: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
com.rabbitmq.client.TopologyRecoveryException: Caught an exception while recovering queue admin.assignments: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverQueues(AutorecoveringConnection.java:571)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverEntities(AutorecoveringConnection.java:523)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.beginAutomaticRecovery(AutorecoveringConnection.java:451)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.access$000(AutorecoveringConnection.java:53)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection$1.shutdownCompleted(AutorecoveringConnection.java:383)
        at com.rabbitmq.client.impl.ShutdownNotifierComponent.notifyListeners(ShutdownNotifierComponent.java:75)
        at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:578)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.rabbitmq.client.AlreadyClosedException: channel is already closed due to clean channel shutdown; protocol method: #method<channel.close>(reply-code=200, reply-text=OK, class-id=0, method-id=0)
        at com.rabbitmq.client.impl.AMQChannel.ensureIsOpen(AMQChannel.java:195)
        at com.rabbitmq.client.impl.AMQChannel.rpc(AMQChannel.java:241)
        at com.rabbitmq.client.impl.AMQChannel.privateRpc(AMQChannel.java:219)
        at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:118)
        at com.rabbitmq.client.impl.ChannelN.queueDeclare(ChannelN.java:844)
        at com.rabbitmq.client.impl.recovery.AutorecoveringChannel.queueDeclare(AutorecoveringChannel.java:266)
        at com.rabbitmq.client.impl.recovery.RecordedQueue.recover(RecordedQueue.java:38)
        at com.rabbitmq.client.impl.recovery.AutorecoveringConnection.recoverQueues(AutorecoveringConnection.java:549)
        ... 7 more
```

**Comment by LGLO** [comment]
This should be fixed by #36 AFAIR

**Comment by notvitor** [comment]
Hi @LGLO !

The bump 1.1.1 contains this fix as well #36?

-V

**Comment by LGLO** [comment]
No, #36 isn't merged yet.

**Comment by pocman** [comment]
@notvitor there is similar issue solved in 3.6.1 but 1.1.1 didn't fixed it. Not the same afterall ^^

**Comment by pocman** [comment]
Now that #36 is merged, could you create a release, I'll give it a try and close the issue if everything is good ;)

**Comment by matemagyari** [comment]
Hi @LGLO, when is the next release due?

**Comment by LGLO** [comment]
I've never release this lib before but I'll try to figure out process and I hope release will be soon.

**Comment by LGLO** [comment]
@matemagyari I've made GH release. I'll make sure it gets to maven but I'm not sure how long will it take.

**Comment by guizmaii** [comment]
Hi, It seems that the v1.1.2 is not yet released in Maven. Any news ?

**Comment by mkiedys** [comment]
Released
